2020-11-02 04:42:05,277:DEBUG:certbot._internal.main:certbot version: 1.9.0
2020-11-02 04:42:05,278:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'rpi.iot.2020@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'sss.rpi-iot.tk']
2020-11-02 04:42:05,279:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-11-02 04:42:05,347:DEBUG:certbot._internal.log:Root logging level set at 20
2020-11-02 04:42:05,348:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-11-02 04:42:05,351:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2020-11-02 04:42:05,365:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fee901fcd90>
Prep: True
2020-11-02 04:42:05,366:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fee901fcd90> and installer None
2020-11-02 04:42:05,366:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-11-02 04:42:05,651:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-11-02 04:42:05,658:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-11-02 04:42:06,499:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-11-02 04:42:06,501:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:42:06 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "grli_JqX0CU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-11-02 04:42:06,502:DEBUG:acme.client:Requesting fresh nonce
2020-11-02 04:42:06,503:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-11-02 04:42:06,713:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-11-02 04:42:06,715:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:42:06 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103inhvVPwM2YA4jQLWkE5qLQBXLi05PVmLXDb-W5loqlM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-11-02 04:42:06,715:DEBUG:acme.client:Storing nonce: 0103inhvVPwM2YA4jQLWkE5qLQBXLi05PVmLXDb-W5loqlM
2020-11-02 04:42:06,716:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:rpi.iot.2020@gmail.com"\n  ],\n  "termsOfServiceAgreed": true\n}'
2020-11-02 04:42:06,729:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogIno3RW0zSHNWUkg4YWZTMWgycjNDTWtXMmRvSjJaaWtYRS1SRmFiYnRxaVllcTJiQ3ZOcXE2WVgzM0pVX094ckhISklrNWgwb3ktZ3lCOFp1aUtsNFl3cDJzZlVyeXY5QXFEcWNKMTd3Sk8xc3VlOThVYVZMeHlyYV9QS3dPb0luMEpQQ2VwbXFoOFZJRnlnMlk2SW1jaXJTSm5EUWJoUm5SOU02bjdWUlFtQXp4Z201UGZ6cWdsS21GZ2tGWG43YlgteWdDR2l3cmQwczZnTWc4TlRhbk9faWFVX0ItMXYzODNPZ0ZaVUlEbFV4TWhmWUJjWnd1LXlKdkZmd090RnpaYk9YTHlzVzUzVjl3MXJpMHhFQ1dCZHVhdlRXWS1HdHdpX1hUZkN4NlFTREE2c2pJNnpqYS1abkhxeUVOYUF0aHFsNzZ3QjlfQVV3dDFYMmFLalV4USIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiMDEwM2luaHZWUHdNMllBNGpRTFdrRTVxTFFCWExpMDVQVm1MWERiLVc1bG9xbE0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1hY2N0In0",
  "signature": "FvVE8oUtYMs9nsw_Zs0ENdYFwyesC1LqHvRv_ZpGaZ5LOqWL9g-fhj4VGfhST5EX0ZScKgTDgLc_agYU6wV_GhoL-aPBBXIUnBTvAa0fTHJJxqw7fLr6fT3sQrcH3d0j--Y8RBCkW8-48pMD9IFwX2q_mnIOl3vPhHs_PORWFhOjKobwUYzPktLOZWgh9ImJ9hgu_7hA4MtYIz_VboY8_azWmYQNqG2CX8zEZ9whllU5iq6X9CUi8gb0LSo-gpW874s8WIFgd8MI5aCctKiButkbgb84IGbw4Zl5kZqltnM-BNyRlyW49apX4uhveDqKJedxNL-x24Tf_s--yqc8IQ",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzpycGkuaW90LjIwMjBAZ21haWwuY29tIgogIF0sCiAgInRlcm1zT2ZTZXJ2aWNlQWdyZWVkIjogdHJ1ZQp9"
}
2020-11-02 04:42:07,018:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 201 564
2020-11-02 04:42:07,020:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 04:42:06 GMT
Content-Type: application/json
Content-Length: 564
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/101055913
Replay-Nonce: 0103CmDdCD69DDaY7WzCPAYg7JZmceDng_V_-4LULxH-Y-A
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "z7Em3HsVRH8afS1h2r3CMkW2doJ2ZikXE-RFabbtqiYeq2bCvNqq6YX33JU_OxrHHJIk5h0oy-gyB8ZuiKl4Ywp2sfUryv9AqDqcJ17wJO1sue98UaVLxyra_PKwOoIn0JPCepmqh8VIFyg2Y6ImcirSJnDQbhRnR9M6n7VRQmAzxgm5PfzqglKmFgkFXn7bX-ygCGiwrd0s6gMg8NTanO_iaU_B-1v383OgFZUIDlUxMhfYBcZwu-yJvFfwOtFzZbOXLysW53V9w1ri0xECWBduavTWY-Gtwi_XTfCx6QSDA6sjI6zja-ZnHqyENaAthql76wB9_AUwt1X2aKjUxQ",
    "e": "AQAB"
  },
  "contact": [
    "mailto:rpi.iot.2020@gmail.com"
  ],
  "initialIp": "60.53.241.89",
  "createdAt": "2020-11-02T04:42:06.938727854Z",
  "status": "valid"
}
2020-11-02 04:42:07,021:DEBUG:acme.client:Storing nonce: 0103CmDdCD69DDaY7WzCPAYg7JZmceDng_V_-4LULxH-Y-A
2020-11-02 04:42:07,026:DEBUG:certbot._internal.reporter:Reporting to user: Your account credentials have been saved in your Certbot configuration directory at /etc/letsencrypt. You should make a secure backup of this folder now. This configuration directory will also contain certificates and private keys obtained by Certbot so making regular backups of this folder is ideal.
2020-11-02 04:42:07,032:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7fee901f1970>)>), contact=('mailto:rpi.iot.2020@gmail.com',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/101055913', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), 331f70515e28b731b0aa2f62a3c69731, Meta(creation_dt=datetime.datetime(2020, 11, 2, 4, 42, 7, tzinfo=<UTC>), creation_host='7a51cc79cdad', register_to_eff=None))>
2020-11-02 04:42:07,035:INFO:certbot._internal.main:Obtaining a new certificate
2020-11-02 04:42:07,270:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
2020-11-02 04:42:07,279:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem
2020-11-02 04:42:07,281:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "sss.rpi-iot.tk"\n    }\n  ]\n}'
2020-11-02 04:42:07,288:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDNDbURkQ0Q2OUREYVk3V3pDUEFZZzdKWm1jZURuZ19WXy00TFVMeEgtWS1BIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "IkxZ0NgvJSalW-Mmf2zForqcN3RC6ghZ4fnpTCI5Dif2aG-Et0xFrKedWNMe54OwoArL7hwHlDP061qtZjyLjoVR38Igp9Y6M93BZSMyUCPT7r42rykNqvgHZQqmvnisAmUS7zi-rqJIvswlZzQucNYOqc_kypWX4Ep4l-WtLRB6KFezmFsmA36ycLOp13MydhG8gCm2L7C8wtsMqUp_yOdUGh-uCMCfKGajR_ym44XCL_g68CW6qPrSFURX2h2IzvzYdOiqyPvE9NIsUKZRlLRzzuH_1koDEx7tS00Vd7wBjhfXNThjhAuTMLUqivrwFhDL03oHBlaJDMitNf1xzw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInNzcy5ycGktaW90LnRrIgogICAgfQogIF0KfQ"
}
2020-11-02 04:42:07,653:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 345
2020-11-02 04:42:07,657:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 04:42:07 GMT
Content-Type: application/json
Content-Length: 345
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/101055913/5994186928
Replay-Nonce: 0103QUA-mWqM7xnMPoi6FmwWJUEObIp168bNgN7zVs6Ro0g
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-09T04:42:07.537574184Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "sss.rpi-iot.tk"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8303865199"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/101055913/5994186928"
}
2020-11-02 04:42:07,658:DEBUG:acme.client:Storing nonce: 0103QUA-mWqM7xnMPoi6FmwWJUEObIp168bNgN7zVs6Ro0g
2020-11-02 04:42:07,666:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:42:07,673:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8303865199:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDNRVUEtbVdxTTd4bk1Qb2k2Rm13V0pVRU9iSXAxNjhiTmdON3pWczZSbzBnIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAzODY1MTk5In0",
  "signature": "Yz_DLB5biJwq7rBp_3R6PxijRduBzLjeD6Rbswsp7UAScjVkwvRKQUqfZHO_wwz5zU3-0J_6Cv1iZs-2L1LNw0j9RLMRrDG4sS8ZUs7uM6mA5eLtalPGmGilT2fhaOhc0XbH31xmATJh7DFTQrPmgpo9ZOmnf7wZ_n9ZYJMB2jcKpuwhXxH2zdSFtmTz6YTwXcKs_w-kLgz7-X-DYOpB5J4ZedyykAKY8PV6cztjtkt0r4rtx96073CXOrrRLuMVVRCk3S_ZIp9jrIojh6oUhTeZa-0wjluaaLzo9WoLzwt-E0N_0y01j-VD25BKnSZ8jqUXVpKsdWiEbsnHa-AEvg",
  "payload": ""
}
2020-11-02 04:42:07,935:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8303865199 HTTP/1.1" 200 792
2020-11-02 04:42:07,937:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:42:07 GMT
Content-Type: application/json
Content-Length: 792
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103HiD6cQ9hbz8XydqdxQnpPF_0M8e7LO_-X1Wr65sy3ec
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "pending",
  "expires": "2020-11-09T04:42:07Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/hH_ZTA",
      "token": "3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/mN_GTg",
      "token": "3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/HZinBQ",
      "token": "3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY"
    }
  ]
}
2020-11-02 04:42:07,937:DEBUG:acme.client:Storing nonce: 0103HiD6cQ9hbz8XydqdxQnpPF_0M8e7LO_-X1Wr65sy3ec
2020-11-02 04:42:07,939:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-11-02 04:42:07,939:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:42:07,940:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2020-11-02 04:42:07,941:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2020-11-02 04:42:07,951:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY
2020-11-02 04:42:07,952:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-11-02 04:42:07,954:DEBUG:acme.client:JWS payload:
b'{}'
2020-11-02 04:42:07,961:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/hH_ZTA:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDNIaUQ2Y1E5aGJ6OFh5ZHFkeFFucFBGXzBNOGU3TE9fLVgxV3I2NXN5M2VjIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My84MzAzODY1MTk5L2hIX1pUQSJ9",
  "signature": "eRz4DdQJGpxtE4zdpbchy6MjUwAwESgRZm0tlQFljEFeRVslKZKBNo2f6VtaYo7x0Gz4aGv_AokX3PMlpN9aUSIa5_OaWtVXHybmICzLvo6-geO4yUWOrN8LuzM2OScjyv6YFll4AUqvSqjDGenBEtcVVQDP88fVQ1vsWcE_WYp3w9w7Q0kEO28tKGxfhZUjbvyI7am4CAn5gn18fKBmi6rBSqRnHbSgnOfMbC--5mwXmbs4j65Tb7NmIAClMT5zbmR38N67WEG_sdQ53NWfAMV7OhBLd7R2A7sgondGrte0PIXRBsm-87Ifq7Voi3_3riXE_za29ZAK8xRGG53hpQ",
  "payload": "e30"
}
2020-11-02 04:42:08,215:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/8303865199/hH_ZTA HTTP/1.1" 200 185
2020-11-02 04:42:08,219:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:42:08 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/8303865199>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/hH_ZTA
Replay-Nonce: 0103Ccle9pvXDtvD6t1o8cVLz3xhLEEWhrldp3_DSK8AnrI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/hH_ZTA",
  "token": "3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY"
}
2020-11-02 04:42:08,221:DEBUG:acme.client:Storing nonce: 0103Ccle9pvXDtvD6t1o8cVLz3xhLEEWhrldp3_DSK8AnrI
2020-11-02 04:42:09,224:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:42:09,233:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8303865199:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDNDY2xlOXB2WER0dkQ2dDFvOGNWTHozeGhMRUVXaHJsZHAzX0RTSzhBbnJJIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAzODY1MTk5In0",
  "signature": "LhNTzhVRtELVyPNtTzDcRmlZqxKWpJFdgoS_N2TGpxXxjImI8J2G0PWlBqbnXFge1ztLqUDEQfEZP8ZNDRy4_vSye-k23fAbU-SIodZJhSNGh4xLLZtMedTn0bssGhyWLG2lKsADCLiE2tnMihNtBgQZP6rBTuexDzLShVukEE-p3u6tVyE8qN3UinMree261-EthrqsTVTutlV-l9gmen9jnYYgc6s6mJeKr0HiooDTo59PqYoaCWzlBt69JYknPu6FheTk1kkPy4Fz2T-GvaMiFKtUpD7DlN9nOx9vMrKTubYMzUJaLGXwbpDyrLFy_5RT66pqURG9bkluHkDKpg",
  "payload": ""
}
2020-11-02 04:42:09,479:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8303865199 HTTP/1.1" 200 962
2020-11-02 04:42:09,481:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:42:09 GMT
Content-Type: application/json
Content-Length: 962
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103hMueq9UfbSuoMTM1Xlb0ViCbmNJ34YOHTlSz_72TuWw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "invalid",
  "expires": "2020-11-09T04:42:07Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8303865199/hH_ZTA",
      "token": "3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY",
      "validationRecord": [
        {
          "url": "http://sss.rpi-iot.tk/.well-known/acme-challenge/3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY",
          "hostname": "sss.rpi-iot.tk",
          "port": "80",
          "addressesResolved": [
            "60.53.241.89"
          ],
          "addressUsed": "60.53.241.89"
        }
      ]
    }
  ]
}
2020-11-02 04:42:09,482:DEBUG:acme.client:Storing nonce: 0103hMueq9UfbSuoMTM1Xlb0ViCbmNJ34YOHTlSz_72TuWw
2020-11-02 04:42:09,483:WARNING:certbot._internal.auth_handler:Challenge failed for domain sss.rpi-iot.tk
2020-11-02 04:42:09,485:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:42:09,486:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: sss.rpi-iot.tk
Type:   connection
Detail: Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY: Connection refused

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2020-11-02 04:42:09,488:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-11-02 04:42:09,488:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-02 04:42:09,488:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-11-02 04:42:09,489:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/3cFRD-kEz2hDDk6NpOQAR9wW7cW0xLZmnu92fMt46UY
2020-11-02 04:42:09,490:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2020-11-02 04:42:09,491:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1362, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1243, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 122, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 418, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2020-11-02 04:42:09,495:ERROR:certbot._internal.log:Some challenges have failed.
