2020-11-02 04:53:36,734:DEBUG:certbot._internal.main:certbot version: 1.9.0
2020-11-02 04:53:36,735:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'rpi.iot.2020@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'sss.rpi-iot.tk']
2020-11-02 04:53:36,736:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-11-02 04:53:36,794:DEBUG:certbot._internal.log:Root logging level set at 20
2020-11-02 04:53:36,795:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-11-02 04:53:36,798:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2020-11-02 04:53:36,811:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fbd2e1ccd60>
Prep: True
2020-11-02 04:53:36,812:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fbd2e1ccd60> and installer None
2020-11-02 04:53:36,812:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-11-02 04:53:36,823:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/101055913', new_authzr_uri=None, terms_of_service=None), 331f70515e28b731b0aa2f62a3c69731, Meta(creation_dt=datetime.datetime(2020, 11, 2, 4, 42, 7, tzinfo=<UTC>), creation_host='7a51cc79cdad', register_to_eff=None))>
2020-11-02 04:53:36,825:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-11-02 04:53:36,829:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-11-02 04:53:37,695:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-11-02 04:53:37,698:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:53:37 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "4qI9yg-BEnE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-11-02 04:53:37,701:INFO:certbot._internal.main:Obtaining a new certificate
2020-11-02 04:53:38,023:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2020-11-02 04:53:38,032:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2020-11-02 04:53:38,035:DEBUG:acme.client:Requesting fresh nonce
2020-11-02 04:53:38,035:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-11-02 04:53:38,247:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-11-02 04:53:38,249:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:53:38 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104PBZwZe1M1_8sdb_mU0zfb-0X8HbqpIbBuLB7mtkyJHE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-11-02 04:53:38,249:DEBUG:acme.client:Storing nonce: 0104PBZwZe1M1_8sdb_mU0zfb-0X8HbqpIbBuLB7mtkyJHE
2020-11-02 04:53:38,250:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "sss.rpi-iot.tk"\n    }\n  ]\n}'
2020-11-02 04:53:38,260:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDRQQlp3WmUxTTFfOHNkYl9tVTB6ZmItMFg4SGJxcEliQnVMQjdtdGt5SkhFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "GNRfopK1iFOcBVUwp1Zn8goS8trQs99tVi_HRFm_kpeAhRzswCyXZulx8fytDCTP9oSh47gfern6XIiYxmcqgw6JENbFclqd0ub0gSqRwSWstxaJH0KIv0lc_DAflA7kLVZaBsyZWqh4DST4fEemeOrLfoVNOUT4wBaBcYQHzPTiJG5aPLOrbBWol_PyFgpaW1tX7x1P51mekGmbbc7OTOnC3RHOijnko9eGnD6PcnY-MHrockv_BCghYFFKgtwB47KyHFEjM6s8k53IvHdbKp-MkPBDuAlfWfkM1aeLatMhB2j4EMenC-HUYQmibxkbXwHM6PtZvfTDZ_hntqTdsw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInNzcy5ycGktaW90LnRrIgogICAgfQogIF0KfQ"
}
2020-11-02 04:53:38,621:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 345
2020-11-02 04:53:38,623:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 04:53:38 GMT
Content-Type: application/json
Content-Length: 345
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/101055913/5994320676
Replay-Nonce: 0104aPO9jyxxSwP-P7GA27ShGkdESq8hciVN39QAepABq3g
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-09T04:53:38.522132297Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "sss.rpi-iot.tk"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304039793"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/101055913/5994320676"
}
2020-11-02 04:53:38,624:DEBUG:acme.client:Storing nonce: 0104aPO9jyxxSwP-P7GA27ShGkdESq8hciVN39QAepABq3g
2020-11-02 04:53:38,625:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:53:38,634:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304039793:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDRhUE85anl4eFN3UC1QN0dBMjdTaEdrZEVTcThoY2lWTjM5UUFlcEFCcTNnIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzA0MDM5NzkzIn0",
  "signature": "fOWICwfBrAKgVeES_S5PRXzkxd4l-NJEXpDQkgnU8pCp2JPwsAhJ_ksLd82h3DJlXt--QGjPLTzCp-LZk26zzOMirDwvbz1waO53nQs2CYYjN5Y2XkBzziISt17ONvgNs7APspup2VRRgsVXHmW1oZxwDtftaK0eJaTYLxDbjCSgpr7FF1C8VkXHdrb5LNtAOUiY1fGKSOf0sMa80BMujHD_buBDdsjVSddFV_-vjpKr0VkE5fK9lOz1VUfWzjpQN8kr3EMd3vxOiNsU0_wZ4gp-c8_-mLdVfSf6f3x3IynWPKD5fLirbs5qwZS-7xLcgPVUVxQjss6KcbFZyeSeKg",
  "payload": ""
}
2020-11-02 04:53:38,872:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8304039793 HTTP/1.1" 200 792
2020-11-02 04:53:38,874:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:53:38 GMT
Content-Type: application/json
Content-Length: 792
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103uyWZeb4exOPEnf96pVx54Yq0W6H4IVjeJyCMrUNBxm0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "pending",
  "expires": "2020-11-09T04:53:38Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/ugyoXw",
      "token": "Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/adMQBg",
      "token": "Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/BZiyxg",
      "token": "Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg"
    }
  ]
}
2020-11-02 04:53:38,874:DEBUG:acme.client:Storing nonce: 0103uyWZeb4exOPEnf96pVx54Yq0W6H4IVjeJyCMrUNBxm0
2020-11-02 04:53:38,876:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-11-02 04:53:38,879:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:53:38,880:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2020-11-02 04:53:38,881:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2020-11-02 04:53:38,891:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg
2020-11-02 04:53:38,893:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-11-02 04:53:38,894:DEBUG:acme.client:JWS payload:
b'{}'
2020-11-02 04:53:38,901:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/ugyoXw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDN1eVdaZWI0ZXhPUEVuZjk2cFZ4NTRZcTBXNkg0SVZqZUp5Q01yVU5CeG0wIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My84MzA0MDM5NzkzL3VneW9YdyJ9",
  "signature": "dAoni2y2wgNPkB5fhGwxKbrrJau9L8Rdqz_hPgyeS-fnwJt3kLI82vKU7ymIH2uy7ax3aMf1AA-AJ1t9yH6VLmMjD1j4dqyuNtCVg4oZ2v6Uf6lg0hYxiSvlD_uQnLuKBvgwBEUdAguBXqHhnWLjXpXvrmWbM4pAP3sNEIZgn03p2XF9_kf6tpdQYGOU1tHrtHmTVPHQHrOXql4yzmF3yLoiWMCXhcJUMbSXEXks7YJqEj4IMsvQHfa2hAsGRlOCIJdEPm9-e2zkEfcUubeoGFEvyVXMnl_FPKrAlbR_5wmCWTYFwx13ZfwIhQEbVkoxQI2wy8fAs-DKH3DkD5-dpg",
  "payload": "e30"
}
2020-11-02 04:53:39,152:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/8304039793/ugyoXw HTTP/1.1" 200 185
2020-11-02 04:53:39,153:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:53:39 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304039793>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/ugyoXw
Replay-Nonce: 0104DxbefGnT4Afd5wceOTBSoai3SqWF0j3XjUi7Nwgeu7E
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/ugyoXw",
  "token": "Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg"
}
2020-11-02 04:53:39,154:DEBUG:acme.client:Storing nonce: 0104DxbefGnT4Afd5wceOTBSoai3SqWF0j3XjUi7Nwgeu7E
2020-11-02 04:53:40,156:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:53:40,164:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304039793:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDREeGJlZkduVDRBZmQ1d2NlT1RCU29haTNTcVdGMGozWGpVaTdOd2dldTdFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzA0MDM5NzkzIn0",
  "signature": "tSlCB6rzrVFaksnSuF4nID9vpVEVjPbnITezDAUyk3vkbHWlqpqm_n_RYc6sidhYfs29-WKLtWRQd-P7rOTitSfDOpNO8_RKRrqaswqNoANBHhp_zQPaomocA6QK7ygkGFMlmsZSzh5DwYP6tVC584PSdy2QFa6s9PczgNPjenPk52FGbQlTHXdMyaGdqSyz1DEGSJIHeNa8pW--VyGWn1UyIHDcu3AH3XPs77ETGZcZLHp9mIGGqkFhkOr1lXxcPcrRwYo27eoDk4Dq4F79wqOV06gURjpnTBKykeQl_YiLTE4uRUKMST5SBlE0lu40KQz0v7nDj0SwMiPHW4T8bA",
  "payload": ""
}
2020-11-02 04:53:40,403:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8304039793 HTTP/1.1" 200 962
2020-11-02 04:53:40,405:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:53:40 GMT
Content-Type: application/json
Content-Length: 962
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104kDE-bvMvQGWhXNYeq0LDeSAX5zlydw-N7TIpqXnZSOc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "invalid",
  "expires": "2020-11-09T04:53:38Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304039793/ugyoXw",
      "token": "Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg",
      "validationRecord": [
        {
          "url": "http://sss.rpi-iot.tk/.well-known/acme-challenge/Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg",
          "hostname": "sss.rpi-iot.tk",
          "port": "80",
          "addressesResolved": [
            "60.53.241.89"
          ],
          "addressUsed": "60.53.241.89"
        }
      ]
    }
  ]
}
2020-11-02 04:53:40,406:DEBUG:acme.client:Storing nonce: 0104kDE-bvMvQGWhXNYeq0LDeSAX5zlydw-N7TIpqXnZSOc
2020-11-02 04:53:40,407:WARNING:certbot._internal.auth_handler:Challenge failed for domain sss.rpi-iot.tk
2020-11-02 04:53:40,408:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:53:40,410:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: sss.rpi-iot.tk
Type:   connection
Detail: Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg: Connection refused

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2020-11-02 04:53:40,412:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-11-02 04:53:40,412:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-02 04:53:40,412:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-11-02 04:53:40,413:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/Z7IbohUlMmOltfoikH4VpNl9Np6EimkWU9xnN0lLjdg
2020-11-02 04:53:40,414:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2020-11-02 04:53:40,415:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1362, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1243, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 122, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 418, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2020-11-02 04:53:40,417:ERROR:certbot._internal.log:Some challenges have failed.
