2020-11-02 04:55:02,279:DEBUG:certbot._internal.main:certbot version: 1.9.0
2020-11-02 04:55:02,280:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'rpi.iot.2020@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'sss.rpi-iot.tk']
2020-11-02 04:55:02,281:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-11-02 04:55:02,353:DEBUG:certbot._internal.log:Root logging level set at 20
2020-11-02 04:55:02,354:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-11-02 04:55:02,357:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2020-11-02 04:55:02,370:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fbc0a9248e0>
Prep: True
2020-11-02 04:55:02,371:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fbc0a9248e0> and installer None
2020-11-02 04:55:02,371:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-11-02 04:55:02,382:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/101055913', new_authzr_uri=None, terms_of_service=None), 331f70515e28b731b0aa2f62a3c69731, Meta(creation_dt=datetime.datetime(2020, 11, 2, 4, 42, 7, tzinfo=<UTC>), creation_host='7a51cc79cdad', register_to_eff=None))>
2020-11-02 04:55:02,384:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-11-02 04:55:02,389:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-11-02 04:55:03,244:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-11-02 04:55:03,249:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:55:03 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "KNoz8bGDnIg": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-11-02 04:55:03,254:INFO:certbot._internal.main:Obtaining a new certificate
2020-11-02 04:55:03,387:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2020-11-02 04:55:03,396:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2020-11-02 04:55:03,398:DEBUG:acme.client:Requesting fresh nonce
2020-11-02 04:55:03,398:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-11-02 04:55:03,605:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-11-02 04:55:03,609:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:55:03 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104XzwfpYpSaJsgkKcYN8mFqzRcJCr_ARXph5z2tMfK1mI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-11-02 04:55:03,609:DEBUG:acme.client:Storing nonce: 0104XzwfpYpSaJsgkKcYN8mFqzRcJCr_ARXph5z2tMfK1mI
2020-11-02 04:55:03,611:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "sss.rpi-iot.tk"\n    }\n  ]\n}'
2020-11-02 04:55:03,622:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDRYendmcFlwU2FKc2drS2NZTjhtRnF6UmNKQ3JfQVJYcGg1ejJ0TWZLMW1JIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "hkEsH9GGP1k5VJ9r3E-RGJ2JCdDHOjZXbtaR73vA5BhpDfhf97b3LB1YG4Wh-LBDIc_d_fhdaikndKGYPTn0gTljiLph9eWYPF1SBhJ4KlJGaFaMbHcm0QaTRDvnSZTA0EohyemvZYUROA5WDvppHALV2tO8VKmhyYgoFHMyHooq7KfvvaZ3VDFgvxR2HK583B909Qtjd0YaWxfpr1F9pgEcFykkj_rZG4LY66Gui2zC3ad-aiH5Te534DtsSZ03GoUwda7Y-HkOZSIvT3r1HOcWYrxGFaL_H77_YdXkZwqjTCyMMTaV8DwgRkh1RlbttJtRYRbVKVT4zctk-CeMYQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInNzcy5ycGktaW90LnRrIgogICAgfQogIF0KfQ"
}
2020-11-02 04:55:04,723:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 345
2020-11-02 04:55:04,728:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 04:55:04 GMT
Content-Type: application/json
Content-Length: 345
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/101055913/5994337124
Replay-Nonce: 0104FNBIAXaWTjmzazAnYYMmL5S_CCB-BdhQES2jxnO_tDg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-09T04:55:04.531587564Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "sss.rpi-iot.tk"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304060825"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/101055913/5994337124"
}
2020-11-02 04:55:04,730:DEBUG:acme.client:Storing nonce: 0104FNBIAXaWTjmzazAnYYMmL5S_CCB-BdhQES2jxnO_tDg
2020-11-02 04:55:04,732:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:55:04,739:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304060825:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDRGTkJJQVhhV1RqbXphekFuWVlNbUw1U19DQ0ItQmRoUUVTMmp4bk9fdERnIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzA0MDYwODI1In0",
  "signature": "gsE3_uPiSmRmL1cxk0x_70-nXXjlGNWAkXJnztFHbvKqnoshrNkaFmPnh6ruSBQ61rylt8nHG_RItOxt3AStb_3JrEBGmIJA-Q0Ph6um0YmBKJdH1hPOl5Zx9GP4Y4Thk0mZLAcLrBix1guqg15iFTTfCRcK-RgoWSbqbu0ZVpB172e01f2ETrd9LDBdgRkEWEAdmiMeoFcbF-dAM0jaglJxqXLEgVyCLss25VMqNYXM2maYA84w0mE0EF_1EgMSL3iG3giFQ130SVWjiiAELYvfMqU8S4jSewn8XBL8xV_jfpC49g7-k3aD7AR3H5spKhTXOxrWyGm8C-4UBP2rQQ",
  "payload": ""
}
2020-11-02 04:55:05,064:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8304060825 HTTP/1.1" 200 792
2020-11-02 04:55:05,068:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:55:04 GMT
Content-Type: application/json
Content-Length: 792
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104GwfWNpZaDaGhESWqO2qQP4bHbPkUAh9RjgPzStuO6j0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "pending",
  "expires": "2020-11-09T04:55:04Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/zGS3yA",
      "token": "ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/uwBIGQ",
      "token": "ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/VEL_ew",
      "token": "ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g"
    }
  ]
}
2020-11-02 04:55:05,070:DEBUG:acme.client:Storing nonce: 0104GwfWNpZaDaGhESWqO2qQP4bHbPkUAh9RjgPzStuO6j0
2020-11-02 04:55:05,073:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-11-02 04:55:05,074:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:55:05,075:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2020-11-02 04:55:05,075:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2020-11-02 04:55:05,083:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g
2020-11-02 04:55:05,084:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-11-02 04:55:05,085:DEBUG:acme.client:JWS payload:
b'{}'
2020-11-02 04:55:05,092:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/zGS3yA:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDRHd2ZXTnBaYURhR2hFU1dxTzJxUVA0YkhiUGtVQWg5UmpnUHpTdHVPNmowIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My84MzA0MDYwODI1L3pHUzN5QSJ9",
  "signature": "dX7_Lm2JDOgMqk7KyZityPl9NtYK-EulNwSMQd8dhvAUId9OzfR-7f7JaiouTmOetRykl0OUL1aAKdajLLLP8atGn6wF7-kOFbBgBM0A249f26dgO29-M9sRODXQaTTwwYB28vHlOmDMAiGl0Zs6UbuUwtxAptevV5J6FSDO1cV8ZjGqj_d-Z4KuUw7--Y3IVEdiahGDyz8MkXKu3GyoVQXFCx4GwhW48WnzOpCF_2aAkGSNWZ3Ip0cHwI7mk-1cagrWCOad5f1YeAhpD7q54BHWekw60X5414BN440BCjV36WGBgH1koh1h02WOkDVc6hkUhbC2CpUmyeho3eoSgg",
  "payload": "e30"
}
2020-11-02 04:55:05,377:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/8304060825/zGS3yA HTTP/1.1" 200 185
2020-11-02 04:55:05,381:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:55:05 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304060825>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/zGS3yA
Replay-Nonce: 0103LFkPFzHpohlX5hU8td_B2NnZiKSNS6u08I6gdkpLC_o
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/zGS3yA",
  "token": "ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g"
}
2020-11-02 04:55:05,383:DEBUG:acme.client:Storing nonce: 0103LFkPFzHpohlX5hU8td_B2NnZiKSNS6u08I6gdkpLC_o
2020-11-02 04:55:06,386:DEBUG:acme.client:JWS payload:
b''
2020-11-02 04:55:06,401:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8304060825:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDU1OTEzIiwgIm5vbmNlIjogIjAxMDNMRmtQRnpIcG9obFg1aFU4dGRfQjJOblppS1NOUzZ1MDhJNmdka3BMQ19vIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzA0MDYwODI1In0",
  "signature": "BmXpbyqoeHng4OTociGojROiS-sD3XRcqtkHzt82VA8iRmZgxV6fOL2iFMfzFLRT86Vyh0cbbbCfZg2vT-n12n5-E3rrB9uj7v3oPVXhq2LYEzArDNqk6hThs3S_AIe5ewcmQO_vJ0dqxVtLFGf2xCJwxtnpCbBVhxFjdTSfIIzbKCch6D2xRVUyjarc3MWgyMlcXSqw2nHJ0XHnhtZ9H97H5ycvXJVIxX68mtb-NXZA0htgMVrN0fBvw6yyuzmSunddUNbfZeS1ZgqJoud6vytTJbDOFw-7Z6k540_ePb3tFfSr1971zGQXjCEZDH8InQJBzl-xYPiLo99Xd1HKxQ",
  "payload": ""
}
2020-11-02 04:55:06,648:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8304060825 HTTP/1.1" 200 962
2020-11-02 04:55:06,653:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 04:55:06 GMT
Content-Type: application/json
Content-Length: 962
Connection: keep-alive
Boulder-Requester: 101055913
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103AkvxfKKitlwltyTlSzgSwSOJPU6tPGajgS0apQx9kKM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sss.rpi-iot.tk"
  },
  "status": "invalid",
  "expires": "2020-11-09T04:55:04Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8304060825/zGS3yA",
      "token": "ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g",
      "validationRecord": [
        {
          "url": "http://sss.rpi-iot.tk/.well-known/acme-challenge/ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g",
          "hostname": "sss.rpi-iot.tk",
          "port": "80",
          "addressesResolved": [
            "60.53.241.89"
          ],
          "addressUsed": "60.53.241.89"
        }
      ]
    }
  ]
}
2020-11-02 04:55:06,655:DEBUG:acme.client:Storing nonce: 0103AkvxfKKitlwltyTlSzgSwSOJPU6tPGajgS0apQx9kKM
2020-11-02 04:55:06,658:WARNING:certbot._internal.auth_handler:Challenge failed for domain sss.rpi-iot.tk
2020-11-02 04:55:06,661:INFO:certbot._internal.auth_handler:http-01 challenge for sss.rpi-iot.tk
2020-11-02 04:55:06,663:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: sss.rpi-iot.tk
Type:   connection
Detail: Fetching http://sss.rpi-iot.tk/.well-known/acme-challenge/ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g: Connection refused

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2020-11-02 04:55:06,666:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-11-02 04:55:06,666:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-02 04:55:06,667:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-11-02 04:55:06,667:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/ybm9_nahn634c45tniLNHC1to0FNPFdMIrIvM44sm8g
2020-11-02 04:55:06,669:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2020-11-02 04:55:06,670:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1362, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1243, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 122, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 418, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2020-11-02 04:55:06,674:ERROR:certbot._internal.log:Some challenges have failed.
